version: 2

defaults: &defaults
  docker:
    - image: circleci/node:carbon
  working_directory: ~/dex

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/dex
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: .


  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/dex
      - run: yarn ci-test

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/dex
      - setup_remote_docker
      - run: |
          TAG=$(git describe --tags)
          docker build -t dex:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $DOCKER_USER/dex:$TAG

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

