
defaults: &defaults
  docker:
    - image: circleci/node:carbon
  working_directory: ~/dex

version: 2
jobs:
  validate:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn ci-test

  deploy:
    <<: *defaults
    steps:
      - setup_remote_docker
      - run: |
        TAG=$(git describe --tags)
        docker build -t dex:$TAG .
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker push $DOCKER_USER/dex:$TAG


workflows:
  version: 2
  validate-and-deploy:
    jobs:
      - validate
      - deploy:
        requires:
          - validate
        filters:
          branches:
            only: master
          tags:
	          only: /^v.*/

